'use client'

import { useState } from 'react'

const copy = {
  en: { about: 'About', services: 'Services', projects: 'Projects', contact: 'Contact', eyebrow: 'Construction & Contracting • Iraq', title: 'Building Iraq’s Future', title2: 'With Precision & Trust', lead: 'Premium finishing works, construction execution and turnkey subcontracting solutions for residential, commercial, hospital and villa projects.', quote: 'Request a Quote', whatsapp: 'WhatsApp' },
  tr: { about: 'Hakkımızda', services: 'Hizmetler', projects: 'Projeler', contact: 'İletişim', eyebrow: 'İnşaat ve Taahhüt • Irak', title: 'Irak’ın Geleceğini İnşa Ediyoruz', title2: 'Hassasiyet ve Güvenle', lead: 'Konut, ticari, hastane ve villa projeleri için kaliteli ince işler, inşaat uygulaması ve anahtar teslim taşeronluk çözümleri.', quote: 'Teklif İste', whatsapp: 'WhatsApp' },
  ar: { about: 'من نحن', services: 'الخدمات', projects: 'المشاريع', contact: 'اتصل بنا', eyebrow: 'الإنشاءات والمقاولات • العراق', title: 'نبني مستقبل العراق', title2: 'بدقة وثقة', lead: 'أعمال تشطيب متميزة وتنفيذ إنشائي وحلول مقاولات فرعية متكاملة للمشاريع السكنية والتجارية والمستشفيات والفلل.', quote: 'اطلب عرضاً', whatsapp: 'واتساب' },
} as const

type Language = keyof typeof copy

export function SiteHeader({ language, setLanguage }: { language: Language; setLanguage: (language: Language) => void }) {
  const t = copy[language]
  return <header className="nav glass"><div className="brand">LAVIN <span>GROUP</span></div><nav><a href="#about">{t.about}</a><a href="#services">{t.services}</a><a href="#projects">{t.projects}</a><a href="#contact">{t.contact}</a></nav><div className="langs">{(['TR', 'EN', 'AR'] as const).map((lang) => <button key={lang} onClick={() => setLanguage(lang.toLowerCase() as Language)} aria-pressed={language === lang.toLowerCase()}>{lang}</button>)}</div></header>
}

export function SiteContent() {
  const [language, setLanguage] = useState<Language>('en')
  const t = copy[language]
  return <><SiteHeader language={language} setLanguage={setLanguage} /><main><section className="hero"><div className="overlay" /><div className="hero-content"><p className="eyebrow">{t.eyebrow}</p><h1>{t.title}<br /><span>{t.title2}</span></h1><p className="lead">{t.lead}</p><div className="actions"><a className="btn primary" href="#quote">{t.quote}</a><a className="btn" href="https://wa.me/9647767736442">{t.whatsapp}</a></div></div></section><section id="about" className="section grid2"><div><p className="eyebrow">About Lavin Group</p><h2>A reliable partner for large-scale projects in Iraq.</h2></div><p>Lavin Group operates in construction, contracting and finishing works with professional Turkish teams, competitive execution capacity and a strong commitment to quality, time and engineering standards.</p></section><section className="section cards3"><div className="card glass"><h3>Mission</h3><p>To deliver high-quality finishing and construction works with trust, speed and professional site discipline.</p></div><div className="card glass"><h3>Vision</h3><p>To become one of Iraq’s most trusted finishing and construction partners for premium developments.</p></div><div className="card glass"><h3>Why Lavin?</h3><p>Turkish professional teams, strong operational capacity, competitive pricing and engineering-controlled delivery.</p></div></section><section id="services" className="section"><p className="eyebrow">Our Services</p><h2>Full finishing &amp; construction execution capacity.</h2><div className="service-list"><span>Ceramic Works</span><span>Marble Works</span><span>Gypsum Board</span><span>Painting</span><span>Screed Works</span><span>Epoxy Flooring</span><span>Waterproofing</span><span>Interior Design</span><span>MEP Coordination</span><span>Ceiling Systems</span></div></section><section id="projects" className="section grid2"><div className="project glass"><p>Ongoing Projects</p><h3>Residential, commercial and healthcare projects across Iraq.</h3></div><div className="project glass"><p>Completed Projects</p><h3>Premium finishing and construction works delivered with quality control.</h3></div></section><section className="section stats"><div><strong>8+</strong><span>Years in Iraq</span></div><div><strong>50+</strong><span>Professional Team Capacity</span></div><div><strong>3</strong><span>Languages</span></div><div><strong>24/7</strong><span>Business Contact</span></div></section><section id="quote" className="section quote glass"><p className="eyebrow">Request a Quotation</p><h2>Send your project details, BOQ, drawings or scope.</h2><a className="btn primary" href="mailto:info@lavingroup-iq.com">info@lavingroup-iq.com</a></section></main><footer id="contact"><div>LAVIN GROUP | Construction &amp; Contracting - Iraq</div><div>07767736442 • 07510511320</div></footer></>
}
